# Generated by Django 3.2.5 on 2021-07-13 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allgoscale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='fill_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
